push with pshtmp

diff --git a/nixos-infect b/nixos-infect
--- a/nixos-infect
+++ b/nixos-infect
@@ -25,15 +25,16 @@ makeConf() {
   # Prevent grep for sending error code 1 (and halting execution) when no lines are selected : https://www.unix.com/man-page/posix/1P/grep
   local IFS=$'\n'
   for trypath in /root/.ssh/authorized_keys /home/$SUDO_USER/.ssh/authorized_keys $HOME/.ssh/authorized_keys; do
-      [[ -r "$trypath" ]] \
-      && keys=$(sed -E 's/^[^#].*[[:space:]]((sk-ssh|sk-ecdsa|ssh|ecdsa)-[^[:space:]]+)[[:space:]]+([^[:space:]]+)([[:space:]]*.*)$/\1 \3\4/' "$trypath") \
-      && [[ ! -z "$keys" ]] \
-      && break
+    [[ -r "$trypath" ]] &&
+      keys=$(sed -E 's/^[^#].*[[:space:]]((sk-ssh|sk-ecdsa|ssh|ecdsa)-[^[:space:]]+)[[:space:]]+([^[:space:]]+)([[:space:]]*.*)$/\1 \3\4/' "$trypath") &&
+      [[ ! -z "$keys" ]] &&
+      break
   done
   local network_import=""
 
   if [ "$PROVIDER" = "hostinger" ]; then
-    kernel_params=$(cat << EOF
+    kernel_params=$(
+      cat <<EOF
       boot.kernelParams = [
         "console=tty1"
         "console=ttyS0,115200"
@@ -42,10 +43,10 @@ EOF
     )
   else
     kernel_params=""
-    fi
+  fi
 
   [[ -n "$doNetConf" ]] && network_import="./networking.nix # generated at runtime by nixos-infect"
-  cat > /etc/nixos/configuration.nix << EOF
+  cat >/etc/nixos/configuration.nix <<EOF
 { ... }: {
   imports = [
     ./hardware-configuration.nix
@@ -65,15 +66,16 @@ EOF
     line=$(echo -n "$line" | sed 's/\r//g')
     trimmed_line=$(echo -n "$line" | xargs)
     echo -n "''$trimmed_line'' "
-  done <<< "$keys")];
-  system.stateVersion = "23.11";
+  done <<<"$keys")];
+  system.stateVersion = "25.11";
   $kernel_params
 }
 EOF
 
   if isEFI; then
     if [[ $bootFs == /boot ]]; then
-      bootcfg=$(cat << EOF
+      bootcfg=$(
+        cat <<EOF
   boot.loader.grub = {
     efiSupport = true;
     efiInstallAsRemovable = true;
@@ -81,9 +83,10 @@ EOF
   };
   fileSystems."$bootFs" = { device = "$esp"; fsType = "vfat"; };
 EOF
-)
+      )
     else
-      bootcfg=$(cat << EOF
+      bootcfg=$(
+        cat <<EOF
   boot.loader = {
     efi.efiSysMountPoint = "/boot/efi";
     grub = {
@@ -94,15 +97,15 @@ EOF
   };
   fileSystems."$bootFs" = { device = "$esp"; fsType = "vfat"; };
 EOF
-)
+      )
     fi
   else
-    bootcfg=$(cat << EOF
+    bootcfg=$(
+      cat <<EOF
   boot.loader.grub.device = "$grubdev";
 EOF
-)
+    )
   fi
-
 
   availableKernelModules=('"ata_piix"' '"uhci_hcd"' '"xen_blkfront"')
   if isX86_64; then
@@ -110,7 +113,7 @@ EOF
   fi
 
   # If you rerun this later, be sure to prune the filesSystems attr
-  cat > /etc/nixos/hardware-configuration.nix << EOF
+  cat >/etc/nixos/hardware-configuration.nix <<EOF
 { modulesPath, ... }:
 {
   imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
@@ -122,20 +125,19 @@ $bootcfg
 }
 EOF
 
-
   [[ -n "$doNetConf" ]] && makeNetworkingConf || true
 }
 
 makeLightsailConf() {
   mkdir -p /etc/nixos
-  cat > /etc/nixos/configuration.nix << EOF
+  cat >/etc/nixos/configuration.nix <<EOF
 { config, pkgs, modulesPath, lib, ... }:
 {
   imports = [ "\${modulesPath}/virtualisation/amazon-image.nix" ];
   boot.loader.grub.device = lib.mkForce "/dev/nvme0n1";
 }
 EOF
-    [[ -n "$doNetConf" ]] && makeNetworkingConf || true
+  [[ -n "$doNetConf" ]] && makeNetworkingConf || true
 }
 
 makeNetworkingConf() {
@@ -148,12 +150,13 @@ makeNetworkingConf() {
   gateway6=$(ip -6 route show dev "$eth0_name" | grep default | sed -r 's|default via ([0-9a-f:]+).*|\1|' || true)
   ether0=$(ip address show dev "$eth0_name" | grep link/ether | sed -r 's|.*link/ether ([0-9a-f:]+) .*|\1|')
 
-  eth1_name=$(ip address show | grep '^3:' | awk -F': ' '{print $2}')||true
-  if [ -n "$eth1_name" ];then
+  eth1_name=$(ip address show | grep '^3:' | awk -F': ' '{print $2}') || true
+  if [ -n "$eth1_name" ]; then
     eth1_ip4s=$(ip address show dev "$eth1_name" | grep 'inet ' | sed -r 's|.*inet ([0-9.]+)/([0-9]+).*|{ address="\1"; prefixLength=\2; }|')
     eth1_ip6s=$(ip address show dev "$eth1_name" | grep 'inet6 ' | sed -r 's|.*inet6 ([0-9a-f:]+)/([0-9]+).*|{ address="\1"; prefixLength=\2; }|' || '')
     ether1=$(ip address show dev "$eth1_name" | grep link/ether | sed -r 's|.*link/ether ([0-9a-f:]+) .*|\1|')
-    interfaces1=$(cat << EOF
+    interfaces1=$(
+      cat <<EOF
       $eth1_name = {
         ipv4.addresses = [$(for a in "${eth1_ip4s[@]}"; do echo -n "
           $a"; done)
@@ -163,7 +166,7 @@ makeNetworkingConf() {
         ];
         };
 EOF
-)
+    )
     extraRules1="ATTR{address}==\"${ether1}\", NAME=\"${eth1_name}\""
   else
     interfaces1=""
@@ -173,14 +176,14 @@ EOF
   readarray nameservers < <(grep ^nameserver /etc/resolv.conf | sed -r \
     -e 's/^nameserver[[:space:]]+([0-9.a-fA-F:]+).*/"\1"/' \
     -e 's/127[0-9.]+/8.8.8.8/' \
-    -e 's/::1/8.8.8.8/' )
+    -e 's/::1/8.8.8.8/')
 
   if [[ "$eth0_name" = eth* ]]; then
     predictable_inames="usePredictableInterfaceNames = lib.mkForce false;"
   else
     predictable_inames="usePredictableInterfaceNames = lib.mkForce true;"
   fi
-  cat > /etc/nixos/networking.nix << EOF
+  cat >/etc/nixos/networking.nix <<EOF
 { lib, ... }: {
   # This file was populated at runtime with the networking
   # details gathered from the active system.
@@ -231,7 +234,7 @@ checkExistingSwap() {
 
 makeSwap() {
   swapFile=$(mktemp /tmp/nixos-infect.XXXXX.swp)
-  dd if=/dev/zero "of=$swapFile" bs=1M count=$((1*1024))
+  dd if=/dev/zero "of=$swapFile" bs=1M count=$((1 * 1024))
   chmod 0600 "$swapFile"
   mkswap "$swapFile"
   swapon -v "$swapFile"
@@ -254,11 +257,14 @@ findESP() {
   esp=""
   for d in /boot/EFI /boot/efi /boot; do
     [[ ! -d "$d" ]] && continue
-    [[ "$d" == "$(df "$d" --output=target | sed 1d)" ]] \
-      && esp="$(df "$d" --output=source | sed 1d)" \
-      && break
+    [[ "$d" == "$(df "$d" --output=target | sed 1d)" ]] &&
+      esp="$(df "$d" --output=source | sed 1d)" &&
+      break
   done
-  [[ -z "$esp" ]] && { echo "WARNING: No ESP mount point found"; return 1; }
+  [[ -z "$esp" ]] && {
+    echo "WARNING: No ESP mount point found"
+    return 1
+  }
   for uuid in /dev/disk/by-uuid/*; do
     [[ $(readlink -f "$uuid") == "$esp" ]] && echo $uuid && return 0
   done
@@ -276,7 +282,7 @@ prepareEnv() {
       bootFs=/boot
     fi
   else
-    for grubdev in /dev/vda /dev/sda /dev/xvda /dev/nvme0n1 ; do [[ -e $grubdev ]] && break; done
+    for grubdev in /dev/vda /dev/sda /dev/xvda /dev/nvme0n1; do [[ -e $grubdev ]] && break; done
   fi
 
   # Retrieve root fs block device
@@ -296,64 +302,96 @@ prepareEnv() {
 
 fakeCurlUsingWget() {
   # Use adapted wget if curl is missing
-  which wget && { \
+  which wget && {
     curl() {
       eval "wget $(
-        (local isStdout=1
-        for arg in "$@"; do
-          case "$arg" in
+        (
+          local isStdout=1
+          for arg in "$@"; do
+            case "$arg" in
             "-o")
-              echo "-O";
+              echo "-O"
               isStdout=0
               ;;
             "-O")
               isStdout=0
               ;;
-            "-L")
-              ;;
+            "-L") ;;
             *)
               echo "$arg"
               ;;
-          esac
-        done;
-        [[ $isStdout -eq 1 ]] && echo "-O-"
-        )| tr '\n' ' '
+            esac
+          done
+          [[ $isStdout -eq 1 ]] && echo "-O-"
+        ) | tr '\n' ' '
       )"
-    }; export -f curl; }
+    }
+    export -f curl
+  }
 }
 
 req() {
-  type "$1" > /dev/null 2>&1 || which "$1" > /dev/null 2>&1
+  type "$1" >/dev/null 2>&1 || which "$1" >/dev/null 2>&1
 }
 
 checkEnv() {
-  [[ "$(whoami)" == "root" ]] || { echo "ERROR: Must run as root"; return 1; }
+  [[ "$(whoami)" == "root" ]] || {
+    echo "ERROR: Must run as root"
+    return 1
+  }
 
   # Perform some easy fixups before checking
   # TODO prevent multiple calls to apt-get update
   (which dnf && dnf install -y perl-Digest-SHA) || true # Fedora 24
-  which bzcat || (which yum && yum install -y bzip2) \
-              || (which apt-get && apt-get update && apt-get install -y bzip2) \
-              || true
-  which xzcat || (which yum && yum install -y xz) \
-              || (which apt-get && apt-get update && apt-get install -y xz-utils) \
-              || true
-  which curl  || fakeCurlUsingWget \
-              || (which apt-get && apt-get update && apt-get install -y curl) \
-              || true
-  which tar || (which yum && yum install -y tar) \
-            || (which apt-get && apt-get update && apt-get install -y tar) \
-            || true
+  which bzcat || (which yum && yum install -y bzip2) ||
+    (which apt-get && apt-get update && apt-get install -y bzip2) ||
+    true
+  which xzcat || (which yum && yum install -y xz) ||
+    (which apt-get && apt-get update && apt-get install -y xz-utils) ||
+    true
+  which curl || fakeCurlUsingWget ||
+    (which apt-get && apt-get update && apt-get install -y curl) ||
+    true
+  which tar || (which yum && yum install -y tar) ||
+    (which apt-get && apt-get update && apt-get install -y tar) ||
+    true
 
-  req curl || req wget || { echo "ERROR: Missing both curl and wget";  return 1; }
-  req bzcat            || { echo "ERROR: Missing bzcat";               return 1; }
-  req xzcat            || { echo "ERROR: Missing xzcat";               return 1; }
-  req groupadd         || { echo "ERROR: Missing groupadd";            return 1; }
-  req useradd          || { echo "ERROR: Missing useradd";             return 1; }
-  req ip               || { echo "ERROR: Missing ip";                  return 1; }
-  req awk              || { echo "ERROR: Missing awk";                 return 1; }
-  req cut || req df    || { echo "ERROR: Missing coreutils (cut, df)"; return 1; }
-  req tar              || { echo "ERROR: Missing tar";                 return 1; }
+  req curl || req wget || {
+    echo "ERROR: Missing both curl and wget"
+    return 1
+  }
+  req bzcat || {
+    echo "ERROR: Missing bzcat"
+    return 1
+  }
+  req xzcat || {
+    echo "ERROR: Missing xzcat"
+    return 1
+  }
+  req groupadd || {
+    echo "ERROR: Missing groupadd"
+    return 1
+  }
+  req useradd || {
+    echo "ERROR: Missing useradd"
+    return 1
+  }
+  req ip || {
+    echo "ERROR: Missing ip"
+    return 1
+  }
+  req awk || {
+    echo "ERROR: Missing awk"
+    return 1
+  }
+  req cut || req df || {
+    echo "ERROR: Missing coreutils (cut, df)"
+    return 1
+  }
+  req tar || {
+    echo "ERROR: Missing tar"
+    return 1
+  }
 
   # On some versions of Oracle Linux these have the wrong permissions,
   # which stops sshd from starting when NixOS boots
@@ -381,8 +419,7 @@ infect() {
   nix-channel --add "https://nixos.org/channels/$NIX_CHANNEL" nixos
   nix-channel --update
 
-  if [[ $NIXOS_CONFIG = http* ]]
-  then
+  if [[ $NIXOS_CONFIG = http* ]]; then
     curl -L $NIXOS_CONFIG -o /etc/nixos/configuration.nix
     unset NIXOS_CONFIG
   fi
@@ -400,7 +437,7 @@ infect() {
   /nix/var/nix/profiles/system/sw/bin/nix-collect-garbage
 
   # Reify resolv.conf
-  [[ -L /etc/resolv.conf ]] && mv -v /etc/resolv.conf /etc/resolv.conf.lnk && cat /etc/resolv.conf.lnk > /etc/resolv.conf
+  [[ -L /etc/resolv.conf ]] && mv -v /etc/resolv.conf /etc/resolv.conf.lnk && cat /etc/resolv.conf.lnk >/etc/resolv.conf
 
   # Set label of root partition
   if [ -n "$newrootfslabel" ]; then
@@ -410,15 +447,19 @@ infect() {
 
   # Stage the Nix coup d'état
   touch /etc/NIXOS
-  echo etc/nixos                  >> /etc/NIXOS_LUSTRATE
-  echo etc/resolv.conf            >> /etc/NIXOS_LUSTRATE
-  echo root/.nix-defexpr/channels >> /etc/NIXOS_LUSTRATE
-  (cd / && ls etc/ssh/ssh_host_*_key* || true) >> /etc/NIXOS_LUSTRATE
+  echo etc/nixos >>/etc/NIXOS_LUSTRATE
+  echo etc/resolv.conf >>/etc/NIXOS_LUSTRATE
+  echo root/.nix-defexpr/channels >>/etc/NIXOS_LUSTRATE
+  (cd / && ls etc/ssh/ssh_host_*_key* || true) >>/etc/NIXOS_LUSTRATE
 
   if isEFI; then
     rm -rf $bootFs.bak
     umount "$esp"
-    mv -v $bootFs $bootFs.bak || { cp -a $bootFs $bootFs.bak ; rm -rf $bootFs/* ; umount $bootFs ; }
+    mv -v $bootFs $bootFs.bak || {
+      cp -a $bootFs $bootFs.bak
+      rm -rf $bootFs/*
+      umount $bootFs
+    }
     mkdir -p $bootFs
     mount "$esp" $bootFs
     find $bootFs -depth ! -path $bootFs -exec rm -rf {} +
@@ -432,21 +473,21 @@ fi
 
 [ "$PROVIDER" = "lightsail" ] && newrootfslabel="nixos"
 if [[ "$PROVIDER" = "digitalocean" ]] || [[ "$PROVIDER" = "servarica" ]] || [[ "$PROVIDER" = "hetznercloud" ]] || [[ "$PROVIDER" = "webdock" ]] || [[ "$PROVIDER" = "layer7" ]] || [[ "$PROVIDER" = "hostinger" ]]; then
-	doNetConf=y # some providers require detailed network config to be generated
+  doNetConf=y # some providers require detailed network config to be generated
 fi
 
 checkEnv
 prepareEnv
 checkExistingSwap
 if [[ -z "$NO_SWAP" ]]; then
-    makeSwap # smallest (512MB) droplet needs extra memory!
+  makeSwap # smallest (512MB) droplet needs extra memory!
 fi
 makeConf
 if [[ -z "$NO_INFECT" ]]; then
-    infect
+  infect
 fi
 if [[ -z "$NO_SWAP" ]]; then
-    removeSwap
+  removeSwap
 fi
 
 if [[ -z "$NO_REBOOT" ]]; then
